- docs/UserGuide.md
and edit minor typos like add to addstu.
Question: should we do this incrementally? i.e. keep making PRs to minor edits on our documentation? Idm doing this
> Update User Guide to use TAPros keywords and phrases 

- docs/UserGuide.md
Made the following changes to the User Guide:
Added details for mark command
Changed 'Person' to 'Student'
Addresses #28
> Update Mark Command in UserGuide.md

- docs/DeveloperGuide.md
UG was previously in scope of this issue, but realised that #24 already fixes that.
> Delstu update DG

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/AddPersonCommand.java
- src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Phone.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/model/person/AddressTest.java
- src/test/java/seedu/address/model/person/EmailTest.java
- src/test/java/seedu/address/model/person/PhoneTest.java
- UI: Move nusnet up in the person card
- addstu now only takes name and nusnet as compulsory argument
- Not sure how to do conditional rendering in javafx. For now, any optional fields are rendered with placeholders (this person does not have <field_name>)
Resolves: https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/44
> Reduce compulsory field for the addstu command

- docs/DeveloperGuide.md
- src/main/java/seedu/address/commons/util/Trie.java
- src/main/java/seedu/address/commons/util/TrieNode.java
- src/test/java/seedu/address/commons/util/TrieNodeTest.java
- src/test/java/seedu/address/commons/util/TrieTest.java
Addresses: #57
Resolves: https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/58
> feat: add trie data structure for autocomplete feature

- docs/DevOps.md
- docs/DeveloperGuide.md
- docs/SettingUp.md
- docs/Testing.md
- docs/index.md
Let's
* Point relevant links to our team repo
* Rename AddressBook to TAPro
> docs: Update documentation links

- src/main/java/seedu/address/MainApp.java
As per the [Dev Ops guide](https://ay2324s2-cs2103t-f13-1.github.io/tp/DevOps.html#making-a-release), we should update the version number here before making the release.
> chore: Update version number to v1.2

- docs/diagrams/ModelClassDiagram.puml
- Added CourseName interface, ReadOnlyCourseName and Course classes
> Added 3 classes to Model Class Diagram

- src/main/java/seedu/address/commons/util/Trie.java
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
- src/main/java/seedu/address/logic/autocomplete/AutoCompleteCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/commons/util/TrieTest.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/autocomplete/AutoCompleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- Update Logic interface to include autocomplete
- Add autocomplete parsing to `AddressBookParser`
- Add `AutoComplete` Interface
- Add `AutoCompleteCommand` that autocompletes Commands
- Add key press listener in `CommandBox` that listens to TAB and autocompletes the given input string
- Review and merge #60 first
- Cannot pass ci because cannot test CommandBox ui (original ab3 app also did not test them)
- No visible UI changes, just quality of life improvements
Resolves: #59
Resolves: #57
> feat: autocomplete command

- src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
- src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
- src/main/java/seedu/address/logic/commands/util/ParameterSyntax.java
Resolves #46 for mark and unmark command!
> Improve mark and unmark ::generatemessageusage

- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/Extensions.css
- src/main/resources/view/PersonListCard.fxml
Improved UI for each Person Card, which now shows Attendance more clearly. Resolves #91.
Patch Coverage is 0% since there was no pre-existing test file for PersonCard.java.
> Improve UI for attendance on PersonCard

- src/main/java/seedu/address/MainApp.java
Update the version number to v1.2.1 for the v1.3 trial release. 
See https://nus-cs2103-ay2324s2.github.io/website/schedule/week10/project.html#6-do-a-trial-jar-release.
> chore: Update version number for trial jar

- src/main/java/seedu/address/model/person/NusNet.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/CommandHistory.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/ui/CommandHistoryTest.java
> Use up-down arrows to navigate previous commands

- src/main/java/seedu/address/ui/CommandBox.java
> feat: Move cursor to end after UP/DOWN

- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/autocomplete/AutoCompleteCommand.java
- src/main/java/seedu/address/logic/commands/util/CommandWordUtil.java
- src/test/java/seedu/address/logic/autocomplete/AutoCompleteCommandTest.java
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/97
> style: refactor autocomplete command initialization

- src/main/java/seedu/address/logic/commands/AddPersonCommand.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/113
> style: improve addstu error message

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/ui/HelpWindow.java
Let's
* Add clear into help window
* Add clear message usage
Resolves #132
> fix: Add Clear into help window

- src/main/java/seedu/address/commons/util/Trie.java
Addresses: https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/224
> docs: update reuse declaration format

- docs/UserGuide.md
> docs: Fix missing commands in command summary

- docs/UserGuide.md
> docs: Remove brackets from addstu example command

- docs/UserGuide.md
> docs: Fix commands for deleting

- src/main/resources/view/PersonListCard.fxml
> Remove apostrophe from attendance label

- docs/UserGuide.md
Reverts AY2324S2-CS2103T-F13-1/tp#234
> Revert "docs: update user guide and make find command docs consistent"

- docs/UserGuide.md
It makes our UG look better.
[TAPro - User Guide.pdf](https://github.com/AY2324S2-CS2103T-F13-1/tp/files/14906455/TAPro.-.User.Guide.pdf)
> docs: Add icons for each heading

- docs/UserGuide.md
Resubmit PR after reverting https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/234
> docs: update user guide and make find command docs consistent

- src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
> Fix typo in Unmark message

- docs/UserGuide.md
> Fix example of addstu that used `add` instead of `addstu`

- docs/UserGuide.md
- docs/_markbind/_macros.nj
Let's
* Tweak image sizes.
* Update keyboard format macro.
* Add more stuff in UG for autocomplete.
* Resolves #221
* resolves #194
* resolves #156
Here's the UG pdf to review: [TAPro - User Guide.pdf](https://github.com/AY2324S2-CS2103T-F13-1/tp/files/14906338/TAPro.-.User.Guide.pdf)
> docs: Autocomplete

- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/AddPersonCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/Command.java
- src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
- src/main/java/seedu/address/logic/commands/SetCourseCommand.java
- src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
- src/test/java/seedu/address/logic/commands/CommandTest.java
- NOTE: need to merge https://github.com/AY2324S2-CS2103T-F13-1/tp/pull/225 first
- Improve code quality of logic manager by applying SLAP
- Add `isModification` method on `Command` class. `LogicManager` checks for this to decide whether or not to update address book
> style: code quality logic manager

- docs/UserGuide.md
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/212
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/169
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/166
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/161
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/200
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/162
> docs: improve addstu command user guide documentation

- docs/diagrams/ArchitectureSequenceDiagram.puml
- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/DeleteSequenceDiagram.puml
- docs/diagrams/ModelClassDiagram.puml
- docs/diagrams/UndoRedoState1.puml
Closes #146 
I'm not 100% certain if in the intermediary-parsing steps it is using capital E as well. Would appreciate any comments or help.
> Update eXXXXXXX to EXXXXXXXX and change Address to Major mentions

- docs/UserGuide.md
> Fix toggle window command for mac users

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/main/java/seedu/address/model/weeknumber/WeekNumber.java
> Improved attendance display on result screen

- docs/UserGuide.md
- Replace all instances of `NUSNET_ID` with `NUSNET`
- Move text wrap response to FAQ
- Update restrictions of `TAG` in keywords
> docs: improve ug with FAQ and update keywords

- src/main/java/seedu/address/ui/CommandBox.java
> Fix autocomplete tab issue

- docs/UserGuide.md
> docs: Add find info

- docs/UserGuide.md
For the boxes, rearranged to match this order:
important -> danger -> warning -> info -> tip
> Change some tips to infos and rearranged boxes

- docs/UserGuide.md
> docs: Add example for recognized prefix

- docs/UserGuide.md
> docs: Add known issue on invalid format no message

- docs/UserGuide.md
Resolves https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/288
> docs: update addstu command summary

- docs/DeveloperGuide.md
Addresses https://github.com/AY2324S2-CS2103T-F13-1/tp/issues/244
> docs: update dg use cases

- docs/UserGuide.md
Let's
- Use bolt icon for danger
- Add other parameters table
- Refactor recognized prefixes table
- Add more terms
- Fix typo
- Sorted tables
- Java version info
Resolves #259
> docs: Improve UG

- docs/DeveloperGuide.md
- docs/diagrams/StorageClassDiagram.puml
- Edited storage puml diagram and notes in DG
- Edited model notes in DG
- Edited user stories in DG (solves #240)
> Update dg setcrs

- docs/UserGuide.md
> docs: Add note for empty tag

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/java/seedu/address/ui/HelpWindowCommandCard.java
Resolves #125 (indirectly as there is no need for this now)
> refactor: Fix long line in HelpWindow.java

- docs/UserGuide.md
> docs: Add name restriction note

- docs/DeveloperGuide.md
- docs/diagrams/CommandHistoryActivityDiagram.puml
Added an activity diagram showcasing how the interaction works.
> Improve Command History implementation

- docs/DeveloperGuide.md
Let's
- Use codeblocks
- Update pagination
> docs: Improve DG

- docs/UserGuide.md
> Setcrs desc ug

- docs/DeveloperGuide.md
- docs/UserGuide.md
Let's
- Improve pages
- Fix setcrs note
> docs: Update DG and DG

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/_markbind/layouts/default.md
Let's
- Update sidebar
- Update wording
- Fix Use case ends
- Update User stories
> docs: Fix docs
